---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k8s-mcp

resources:
  - ../

patches:
  - target:
      kind: Namespace
    patch: |-
      - op: replace
        path: /metadata/name
        value: k8s-mcp

# Made with Bob
