quarkus.tls.tls-disabled.trust-all=true
quarkus.tls.tls-disabled.hostname-verification-algorithm=NONE

quarkus.rest-client.cryostat.url=https://localhost:8443
quarkus.rest-client.cryostat.verify-host=false
quarkus.rest-client.cryostat.tls-configuration-name=tls-disabled

cryostat.auth.username=user
cryostat.auth.password=pass
