quarkus.log.file.enable=true
quarkus.log.file.path=cryostat-mcp.log

quarkus.rest-client.follow-redirects=true

quarkus.rest-client.cryostat.url=""
quarkus.rest-client.cryostat.verify-host=true

quarkus.package.uber-jar=true
