quarkus.http.test-port=0

quarkus.mcp.server.enabled=false
quarkus.kubernetes-client.trust-certs=true

quarkus.rest-client.logging.scope=request-response
quarkus.rest-client.logging.body-limit=1024

quarkus.arc.remove-unused-beans=false