apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cryostat-k8s-multi-mcp.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cryostat-k8s-multi-mcp.labels" . | nindent 4 }}