quarkus.log.console.enabled=false
quarkus.log.file.enabled=true
quarkus.log.file.path=cryostat-mcp.log

cryostat.auth.value=

quarkus.rest-client.follow-redirects=true
quarkus.rest-client.cryostat.url=""
quarkus.rest-client.cryostat.verify-host=true
quarkus.smallrye-graphql-client.cryostat.url=""
quarkus.smallrye-graphql-client.cryostat.header.Authorization=${cryostat.auth.value}

quarkus.package.jar.type=uber-jar
