quarkus.tls.tls-disabled.trust-all=true
quarkus.tls.tls-disabled.hostname-verification-algorithm=NONE

cryostat.auth.value=Basic dXNlcjpwYXNz

quarkus.rest-client.cryostat.url=https://localhost:8443/
quarkus.rest-client.cryostat.verify-host=false
quarkus.rest-client.cryostat.tls-configuration-name=tls-disabled
quarkus.smallrye-graphql-client.cryostat.tls-configuration-name=tls-disabled
quarkus.smallrye-graphql-client.cryostat.url=${quarkus.rest-client.cryostat.url}/api/v4/graphql
