kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cryostat-mcp-e2e
nodes:
  - role: control-plane
    extraPortMappings:
      # Cryostat c1 HTTP
      - containerPort: 30080
        hostPort: 8080
        protocol: TCP
      # Cryostat c2 HTTP
      - containerPort: 30081
        hostPort: 8081
        protocol: TCP
      # k8s-multi-mcp HTTP
      - containerPort: 30082
        hostPort: 8082
        protocol: TCP